export const BUSINESS_CATEGORIES = [

    // ── Food & Hospitality ──────────────────────────────────────────
    "Hotels & Resorts",
    "Guest Houses & Lodges",
    "Motels & Inns",
    "Restaurants & Cafes",
    "Fast Food & Bukas",
    "Mama Put & Local Canteens",
    "Suya & Pepper Soup Spots",
    "Bakery & Confectionery",
    "Catering Services",
    "Shawarma & Grills",
    "Ice Cream & Desserts",
    "Juice Bars & Smoothies",
    "Pubs & Beer Parlours",
    "Nightclubs & Lounges",
    "Bars & Cocktail Lounges",
    "Chophouses",
    "Bukka & Buka Joints",
    "Pepper Soup Joints",
    "Nkwobi & Isi Ewu Spots",
    "Bole & Fish Spots",
    "Akara & Moi Moi Sellers",
    "Puff Puff & Chin Chin Sellers",
    "Roasted Corn & Plantain Spots",
    "Noodles & Indomie Spots",
    "Amala & Ewedu Joints",
    "Banga Soup Restaurants",
    "Afang & Edikaikong Spots",
    "Egusi & Ogbono Restaurants",
    "Jollof Rice Specialists",
    "Ofada Rice Sellers",
    "Tuwo & Miyan Kuka Spots",
    "Kilishi & Suya Sellers",
    "Zobo & Kunu Drink Sellers",
    "Palm Wine Spots",
    "Coconut Water Vendors",
    "Groundnut & Kuli-Kuli Sellers",
    "Catfish & Tilapia Restaurants",
    "Seafood Restaurants",
    "Vegetarian & Vegan Restaurants",
    "Chinese & Asian Restaurants",
    "Lebanese & Middle Eastern Food",
    "Continental Restaurants",
    "Pizza & Pasta Restaurants",
    "Burger Joints",
    "Sandwich & Wraps",
    "Food Delivery Services",
    "Cloud Kitchens",
    "Canteen & Cafeteria Services",

    // ── Retail & Trade ──────────────────────────────────────────────
    "Supermarkets & Hypermarkets",
    "Provision Stores",
    "Mini Marts & Kiosks",
    "Open Markets & Stalls",
    "Wholesale & Distribution",
    "Importers & Exporters",
    "Fashion & Clothing",
    "Shoes & Footwear",
    "Bags & Accessories",
    "Jewellery & Watches",
    "Fabrics & Textiles",
    "Ankara & Aso-Oke Sellers",
    "Lace & George Fabric Sellers",
    "Adire & Tie-Dye Sellers",
    "Beads & Accessories",
    "Wigs & Hair Extensions",
    "Cosmetics & Beauty Products",
    "Perfumes & Fragrances",
    "Baby Products & Stores",
    "Children's Clothing & Toys",
    "Furniture & Decor",
    "Bedding & Mattresses",
    "Curtains & Blinds",
    "Kitchenware & Cookware",
    "Household Appliances",
    "Electronics & Gadgets",
    "Phone Accessories",
    "Computer Hardware & Accessories",
    "Office Supplies & Stationery",
    "Books & Educational Materials",
    "Musical Instruments",
    "Sports Equipment",
    "Gym Equipment",
    "Farming Tools & Equipment",
    "Building Materials",
    "Paints & Coatings",
    "Tiles & Flooring",
    "Roofing Materials",
    "Plumbing Materials",
    "Electrical Materials",
    "Sanitary Wares",
    "Glass & Aluminium Products",
    "Doors & Windows",
    "Nails, Bolts & Hardware",
    "Lubricants & Chemicals",
    "Petroleum Products",
    "Gas & Cooking Fuel",
    "Charcoal & Firewood Sellers",
    "Second-Hand Goods (Tokunbo)",
    "Antiques & Collectibles",
    "Gift Shops",
    "Souvenir & Craft Shops",
    "Religious Items & Bookshops",
    "Lottery & Scratch Cards",
    "Recharge Card Sellers",
    "E-commerce Stores",
    "Online Marketplaces",

    // ── Technology & IT ─────────────────────────────────────────────
    "Information Technology",
    "Software Development",
    "Web Design & Development",
    "Mobile App Development",
    "Cybersecurity Services",
    "Cloud Computing Services",
    "Data Analytics & AI",
    "IT Support & Maintenance",
    "Network & Infrastructure",
    "CCTV & Surveillance Systems",
    "Telecommunications",
    "Internet Service Providers",
    "Satellite TV & DSTV Installers",
    "Phone Repairs",
    "Computer Repairs",
    "Printer & Copier Repairs",
    "Data Recovery Services",
    "Bulk SMS & Email Marketing",
    "Digital Marketing",
    "Social Media Management",
    "SEO & Content Marketing",
    "Graphic Design",
    "Animation & Motion Graphics",
    "UI/UX Design",
    "Printing & Publishing",
    "Advertising & PR",
    "Branding & Identity",
    "Photography & Video",
    "Drone Photography",
    "Film & TV Production",
    "Music Production & Studios",
    "Podcast Studios",
    "Media & Journalism",

    // ── Healthcare & Wellness ───────────────────────────────────────
    "Hospitals & Clinics",
    "General Practitioners (GP)",
    "Specialist Hospitals",
    "Maternity & Birthing Centres",
    "Paediatric Clinics",
    "Dental Clinics",
    "Eye Clinics & Opticians",
    "ENT Specialists",
    "Orthopaedic Clinics",
    "Cardiology Centres",
    "Dermatology Clinics",
    "Psychiatric & Mental Health",
    "Physiotherapy & Rehab",
    "Dialysis Centres",
    "Diagnostic & Lab Services",
    "Radiology & Imaging",
    "Blood Banks",
    "Pharmacies & Chemists",
    "Herbal Medicine & Naturopathy",
    "Traditional Medicine (NAFDAC)",
    "Veterinary Services",
    "Pet Clinics & Grooming",
    "Spas & Wellness Centres",
    "Massage Therapy",
    "Yoga & Meditation Centres",
    "Gyms & Fitness Centres",
    "Nutrition & Dietetics",
    "Ambulance Services",
    "Home Care & Nursing",
    "Elderly Care Homes",
    "Disability Support Services",

    // ── Education & Training ────────────────────────────────────────
    "Nursery & Primary Schools",
    "Secondary Schools",
    "Universities & Polytechnics",
    "Colleges of Education",
    "Vocational & Technical Schools",
    "Private Tutors & Lesson Teachers",
    "Coaching Centres & Lesson Centres",
    "JAMB & WAEC Prep Centres",
    "Computer Training Centres",
    "Coding & Tech Bootcamps",
    "Language Schools",
    "Driving Schools",
    "Culinary Schools",
    "Fashion & Design Schools",
    "Music & Arts Schools",
    "Dance Schools",
    "Sports Academies",
    "Religious Schools & Madrasas",
    "Montessori Schools",
    "Special Needs Schools",
    "Creches & Daycare Centres",
    "After-School Programmes",
    "Online Learning Platforms",
    "Professional Certification Centres",
    "ICAN & ACCA Training",
    "NYSC Orientation Camps",

    // ── Finance & Professional Services ────────────────────────────
    "Commercial Banks",
    "Microfinance Banks",
    "Mortgage Banks",
    "Investment & Asset Management",
    "Stockbrokers & Securities",
    "Insurance Companies",
    "Insurance Brokers",
    "Pension Fund Administrators",
    "Forex & Bureau de Change",
    "Cryptocurrency Exchanges",
    "POS Services & Agents",
    "Mobile Money Agents",
    "Cooperative Societies",
    "Thrift & Savings (Ajo/Esusu)",
    "Accounting & Auditing",
    "Tax Consultants",
    "Legal Services & Law Firms",
    "Notary & Documentation",
    "Business Consultancy",
    "Management Consulting",
    "HR & Recruitment Agencies",
    "Payroll Services",
    "Company Registration (CAC)",
    "Patent & Trademark Services",
    "Real Estate Agents",
    "Property Developers",
    "Property Management",
    "Mortgage & Housing Finance",
    "Land Surveyors",
    "Valuers & Estate Surveyors",

    // ── Construction & Building ─────────────────────────────────────
    "Construction & Engineering",
    "Civil Engineering",
    "Structural Engineering",
    "Quantity Surveyors",
    "Architects",
    "Town Planners",
    "Bricklayers & Masons",
    "Block Industry",
    "Concrete & Screeding",
    "Plumbing & Pipefitting",
    "Electrical Installation",
    "Welding & Fabrication",
    "Carpenters & Woodwork",
    "Aluminium & Steel Works",
    "Roofing Contractors",
    "Tiling & Flooring",
    "Painters & Decorators",
    "Interior Design",
    "Landscaping & Gardening",
    "Swimming Pool Construction",
    "Borehole Drilling",
    "Water Supply & Treatment",
    "Septic Tank & Drainage",
    "Scaffolding Services",
    "Demolition Services",
    "Road Construction",
    "Bridge & Infrastructure",

    // ── Automotive ──────────────────────────────────────────────────
    "Car Dealerships (New)",
    "Car Dealerships (Tokunbo)",
    "Motorcycle & Tricycle Sales",
    "Auto Repairs & Mechanics",
    "Panel Beating & Spray Painting",
    "Auto Electricians",
    "Tyre Services & Vulcanisers",
    "Car Wash & Detailing",
    "Auto Parts & Accessories",
    "Lubricants & Engine Oil",
    "Filling Stations & Petrol Stations",
    "LPG & CNG Stations",
    "Vehicle Inspection & Testing",
    "Driving Schools",
    "Car Hire & Rentals",
    "Ride-Hailing Services",
    "Truck & Heavy Equipment Sales",
    "Marine & Boat Services",
    "Aircraft & Aviation Services",

    // ── Agriculture & Food Production ──────────────────────────────
    "Crop Farming",
    "Rice Farming & Milling",
    "Cassava & Yam Farming",
    "Maize & Sorghum Farming",
    "Vegetable & Fruit Farming",
    "Cocoa & Coffee Farming",
    "Palm Oil Production",
    "Groundnut & Sesame Farming",
    "Poultry Farming",
    "Cattle & Livestock Farming",
    "Goat & Sheep Farming",
    "Pig Farming",
    "Fish Farming & Aquaculture",
    "Snail Farming",
    "Bee Keeping & Honey Production",
    "Mushroom Farming",
    "Greenhouse Farming",
    "Agro-Processing & Milling",
    "Fertiliser & Agro-Chemicals",
    "Irrigation & Farm Equipment",
    "Agro-Tech & Precision Farming",
    "Veterinary Supplies",
    "Cold Chain & Food Storage",
    "Abattoirs & Meat Processing",
    "Dairy & Milk Processing",
    "Flour Milling",
    "Breweries & Distilleries",
    "Soft Drink & Bottled Water",
    "Packaged Food Manufacturing",
    "Spices & Seasoning Production",

    // ── Energy & Utilities ──────────────────────────────────────────
    "Solar & Renewable Energy",
    "Solar Panel Installation",
    "Inverter & Battery Sales",
    "Generator Sales",
    "Generator Repairs & Servicing",
    "Electrical Contractors",
    "Power Distribution",
    "Oil & Gas Services",
    "Gas Pipeline & Distribution",
    "Petroleum Engineering",
    "Borehole & Water Supply",
    "Water Treatment Plants",
    "Waste Management & Recycling",
    "Environmental Consultancy",

    // ── Logistics & Transport ───────────────────────────────────────
    "Logistics & Courier Services",
    "Haulage & Trucking",
    "Dispatch Riders",
    "Freight Forwarding",
    "Customs Clearing Agents",
    "Warehousing & Storage",
    "Cold Storage & Refrigeration",
    "Moving & Relocation Services",
    "Bus & Coach Services",
    "Taxi & Cab Services",
    "Boat & Ferry Services",
    "Air Cargo Services",
    "Travel Agencies",
    "Tour Operators",
    "Visa & Immigration Services",
    "Ticketing Offices",

    // ── Personal & Beauty Services ──────────────────────────────────
    "Barbing Salons",
    "Beauty Salons & Hair Salons",
    "Nail Technicians & Nail Salons",
    "Makeup Artists",
    "Bridal Makeup & Styling",
    "Lash & Brow Studios",
    "Tattoo & Body Art",
    "Tailoring & Fashion Design",
    "Dry Cleaning & Laundry",
    "Shoe Cobbling & Repairs",
    "Bag Repairs",
    "Jewellery Making & Repairs",
    "Embroidery & Monogramming",
    "Wig Making & Styling",
    "Braiding & Weaving Salons",
    "Locs & Dreadlocks Stylists",
    "Barbers & Groomers",
    "Massage & Body Therapy",
    "Spa & Relaxation Centres",
    "Manicure & Pedicure",
    "Eyebrow Threading & Waxing",
    "Teeth Whitening Studios",
    "Slimming & Weight Loss Centres",

    // ── Events & Entertainment ──────────────────────────────────────
    "Event Planning & Management",
    "Wedding Planners",
    "Birthday Party Planners",
    "Corporate Event Organisers",
    "Event Halls & Venues",
    "Outdoor Event Spaces",
    "DJ & Sound Rentals",
    "Live Band & Musicians",
    "MC & Compere Services",
    "Ushering & Protocol Services",
    "Catering for Events",
    "Cake & Pastry for Events",
    "Decoration & Floral Services",
    "Tent & Chair Rentals",
    "Bouncy Castle & Rides",
    "Fireworks & Pyrotechnics",
    "Cinemas & Movie Theatres",
    "Amusement Parks",
    "Gaming & Arcade Centres",
    "Bowling Alleys",
    "Escape Rooms",
    "Comedy Shows & Theatres",
    "Concerts & Live Events",
    "Sports Betting Shops",
    "Lottery & Gaming Shops",

    // ── Security & Safety ───────────────────────────────────────────
    "Security Companies",
    "Armed Guards & Escorts",
    "CCTV & Alarm Installation",
    "Access Control Systems",
    "Cybersecurity Firms",
    "Fire Safety & Extinguishers",
    "Safety Equipment Suppliers",
    "Private Investigators",
    "Background Check Services",

    // ── Cleaning & Sanitation ───────────────────────────────────────
    "Domestic Cleaning Services",
    "Industrial & Office Cleaning",
    "Post-Construction Cleaning",
    "Fumigation & Pest Control",
    "Waste Collection & Disposal",
    "Sewage & Septic Services",
    "Laundry & Dry Cleaning",
    "Carpet & Upholstery Cleaning",
    "Pool Cleaning & Maintenance",

    // ── Religious & Community ───────────────────────────────────────
    "Churches",
    "Mosques",
    "Synagogues & Temples",
    "Religious Bookshops",
    "NGOs & Non-Profits",
    "Foundations & Charities",
    "Community Associations",
    "Youth Organisations",
    "Women's Groups",
    "Political Parties & Offices",
    "Government Agencies",
    "Embassies & Consulates",
    "Police Stations",
    "Fire Stations",
    "Hospitals (Government)",
    "Post Offices",
    "NIPOST & Courier Offices",
    "NAFDAC Offices",
    "FIRS & Tax Offices",
    "CAC Offices",
    "NCC & Regulatory Bodies",

    // ── Sports & Recreation ─────────────────────────────────────────
    "Football Clubs & Academies",
    "Basketball Courts",
    "Tennis Courts",
    "Swimming Pools",
    "Golf Courses",
    "Gyms & Fitness Centres",
    "Martial Arts & Boxing Gyms",
    "Cycling Clubs",
    "Athletics Tracks",
    "Sports Complexes",
    "Stadiums",
    "Recreational Parks",
    "Zoos & Wildlife Parks",
    "Museums & Cultural Centres",
    "Libraries",
    "Art Galleries",

    // ── Miscellaneous ───────────────────────────────────────────────
    "AC & Refrigeration Services",
    "Washing Machine Repairs",
    "TV & Electronics Repairs",
    "Furniture Repairs & Upholstery",
    "Key Cutting & Locksmith",
    "Vulcanisers",
    "Photocopy & Scanning",
    "Lamination & Binding",
    "Passport & ID Photo Studios",
    "Cybercafes & Business Centres",
    "Secretarial Services",
    "Translation & Interpretation",
    "Sign Writing & Signage",
    "Neon & LED Sign Makers",
    "Embossing & Engraving",
    "Rubber Stamp Makers",
    "Uniform & Workwear Suppliers",
    "Safety Wear & PPE Suppliers",
    "Cleaning Supplies",
    "Packaging Materials",
    "Plastic & Rubber Products",
    "Foam & Mattress Manufacturers",
    "Textile Mills",
    "Leather Works",
    "Shoe Manufacturing",
    "Bag Manufacturing",
    "Candle & Soap Making",
    "Detergent & Cleaning Products",
    "Cosmetics Manufacturing",
    "Herbal Products",
    "Incense & Aromatherapy",
    "Pet Shops & Supplies",
    "Aquarium & Fish Supplies",
    "Flower Shops & Florists",
    "Plant Nurseries",
    "Seed & Seedling Suppliers",
    "Irrigation Equipment",
    "Fishing Equipment & Supplies",
    "Hunting & Outdoor Gear",
    "Camping & Adventure Gear",
    "Bicycle Sales & Repairs",
    "Skateboard & Scooter Shops",
    "Toy Shops",
    "Hobby & Craft Shops",
    "Stationery & Art Supplies",
    "Bookshops",
    "Magazine & Newspaper Stands",
    "Lottery Kiosks",
    "ATM Locations",
    "Filling Stations",
    "Weighbridges",
    "Cold Rooms & Freezer Rentals",
    "Event Equipment Rentals",
    "Tool & Equipment Hire",
    "Scaffolding Hire",
    "Generator Hire",
    "Tent & Canopy Hire",
    "Costume & Prop Hire",
    "Car Boot Sales",
    "Auction Houses",
    "Pawnshops",
    "Money Lenders",
    "Debt Recovery Agencies",
    "Credit Bureaus",
    "Mortgage Brokers",
    "Leasing Companies",
    "Hire Purchase Services",
    "Cooperative Thrift Societies",

    // ── Trades & Skilled Professions ────────────────────────────────
    "Tailors & Seamstresses",
    "Carpenters",
    "Cabinet Makers",
    "Furniture Makers",
    "Upholsterers",
    "Painters",
    "Plasterers",
    "Tilers",
    "Roofers",
    "Bricklayers",
    "Plumbers",
    "Electricians",
    "Welders",
    "Blacksmiths",
    "Glaziers (Glass Fitters)",
    "Scaffolders",
    "Concrete Workers",
    "Drainage & Sewage Workers",
    "Borehole Drillers",
    "Mechanics",
    "Auto Electricians",
    "Panel Beaters",
    "Spray Painters (Auto)",
    "Tyre Fitters & Vulcanisers",
    "Refrigerator & Freezer Technicians",
    "Air Conditioner Technicians",
    "Washing Machine Technicians",
    "TV & Electronics Technicians",
    "Generator Technicians",
    "Solar Panel Installers",
    "Inverter Technicians",
    "CCTV & Alarm Installers",
    "Satellite & DSTV Installers",
    "Mobile Phone Repairers",
    "Laptop & Computer Repairers",
    "Computer Engineers",
    "Network Engineers",
    "IT Support Technicians",
    "Printer Repairers",
    "Photocopier Technicians",
    "Locksmiths",
    "Security Door Installers",
    "Fumigators",
    "Pest Control Technicians",
    "Cleaners & Janitors",
    "Laundry Workers",
    "Ironing Services",
    "Shoe Cobblers & Repairers",
    "Bag Repairers",
    "Watchmakers & Watch Repairers",
    "Jewellery Repairers",
    "Barbers",
    "Hairdressers & Stylists",
    "Makeup Artists",
    "Nail Technicians",
    "Massage Therapists",
    "Cooks & Private Chefs",
    "Bakers",
    "Caterers",
    "Nannies & Babysitters",
    "Housekeepers",
    "Gardeners & Landscapers",
    "Drivers (Private & Commercial)",
    "Dispatch Riders",
    "Truck Drivers",
    "Bus Drivers",
    "Boat Operators",
    "Security Guards",
    "Bouncers",
    "Bodyguards",
    "Photographers",
    "Videographers",
    "Graphic Designers",
    "Web Developers",
    "App Developers",
    "Content Writers",
    "Translators & Interpreters",
    "Typists & Data Entry Clerks",
    "Accountants",
    "Bookkeepers",
    "Tax Consultants",
    "Lawyers & Solicitors",
    "Estate Agents",
    "Surveyors",
    "Architects",
    "Engineers (Civil)",
    "Engineers (Structural)",
    "Engineers (Mechanical)",
    "Engineers (Electrical)",
    "Engineers (Chemical)",
    "Engineers (Petroleum)",
    "Quantity Surveyors",
    "Town Planners",
    "Interior Decorators",
    "Event Planners",
    "Wedding Planners",
    "DJs",
    "Musicians & Bands",
    "MCs & Comperes",
    "Ushers",
    "Tutors & Home Teachers",
    "Driving Instructors",
    "Fitness Trainers",
    "Nutritionists & Dietitians",
    "Nurses",
    "Midwives",
    "Pharmacists",
    "Doctors (General Practice)",
    "Dentists",
    "Opticians",
    "Physiotherapists",
    "Psychologists & Counsellors",
    "Veterinarians",

    // ── Farm Produce & Fresh Food ────────────────────────────────────
    "Farm Produce Sellers",
    "Fresh Vegetable Sellers",
    "Fresh Fruit Sellers",
    "Tomato & Pepper Sellers",
    "Onion & Garlic Sellers",
    "Yam & Cassava Sellers",
    "Plantain & Banana Sellers",
    "Maize & Corn Sellers",
    "Rice Sellers (Local & Foreign)",
    "Beans & Legumes Sellers",
    "Palm Oil Sellers",
    "Groundnut Oil Sellers",
    "Crayfish & Stockfish Sellers",
    "Dried Fish Sellers",
    "Fresh Fish Sellers",
    "Fresh Meat Sellers",
    "Chicken & Poultry Sellers",
    "Goat & Ram Sellers",
    "Cow Meat (Beef) Sellers",
    "Pork Sellers",
    "Egg Sellers",
    "Milk & Dairy Sellers",
    "Honey Sellers",
    "Spices & Condiments Sellers",
    "Ogiri & Locust Beans Sellers",
    "Iru & Dawadawa Sellers",
    "Garri Sellers",
    "Semovita & Flour Sellers",
    "Frozen Food Sellers",
    "Organic Produce Sellers",
    "Farmers Market Stalls",

    // ── Spare Parts & Auto Accessories ──────────────────────────────
    "Car Spare Parts",
    "Motorcycle Spare Parts Dealers",
    "Truck & Heavy Vehicle Parts",
    "Engine Parts Dealers",
    "Gear Box & Transmission Parts",
    "Brake Parts & Pads",
    "Electrical Auto Parts",
    "Body Parts & Panels",
    "Tyres & Rims Dealers",
    "Battery Dealers (Auto)",
    "Lubricants & Engine Oil Dealers",
    "Tokunbo (Used) Spare Parts",
    "New Spare Parts Dealers",
    "Chinese Spare Parts Dealers",
    "European Car Parts",
    "Japanese Car Parts",
    "American Car Parts",

    // ── Mobile Phones & Gadgets ──────────────────────────────────────
    "Mobile Phone Shops",
    "Smartphone Dealers",
    "iPhone & Apple Dealers",
    "Samsung & Android Dealers",
    "Tecno & Itel Dealers",
    "Used (Tokunbo) Phone Dealers",
    "Phone Accessories Shops",
    "Phone Cases & Screen Guards",
    "Chargers & Cables Sellers",
    "Earphones & Headphones",
    "Power Banks Sellers",
    "Smartwatch Dealers",
    "Tablet & iPad Dealers",
    "Mobile Phone Repairers",
    "Screen Replacement Services",
    "Battery Replacement Services",
    "Software & Flashing Services",

    // ── Computer & IT Equipment ──────────────────────────────────────
    "Computer Shops",
    "Laptop Dealers",
    "Desktop Computer Dealers",
    "Used (Tokunbo) Laptop Dealers",
    "Computer Accessories Shops",
    "Keyboards & Mouse Sellers",
    "Monitors & Screens",
    "Printers & Scanners",
    "Ink & Toner Cartridges",
    "Flash Drives & Memory Cards",
    "External Hard Drives",
    "Networking Equipment",
    "Routers & Modems",
    "UPS & Power Backup",
    "Computer Bags & Cases",
    "Gaming PCs & Consoles",
    "Gaming Accessories",
    "CCTV Cameras & Equipment",
    "Projectors & Screens",

    // ── Drivers & Transport Services ────────────────────────────────
    "Private Car Hire Drivers",
    "Airport Transfer Services",
    "Wedding Car Hire",
    "School Bus Services",
    "Staff Bus Services",
    "Long Distance Drivers",
    "Truck Hire Services",
    "Tipper Truck Hire",
    "Crane & Heavy Equipment Operators",
    "Forklift Operators",
    "Boat & Ferry Operators",

    // ── Security Services ────────────────────────────────────────────
    "Security Guard Companies",
    "Residential Security Services",
    "Commercial Security Services",
    "Event Security Services",
    "VIP Protection & Bodyguards",
    "Cash-in-Transit Services",
    "Security Patrol Services",
    "Dog Security Services",
    "Electronic Security Systems",
    "Security Consulting",
    "Background Verification Services",
    "Business Centres (Xerox & Printing)",
    "Photocopying Services",
    "Binding & Lamination Services",
    "Stationery Shops",
    "Office Furniture Suppliers",
    "Office Equipment Sales & Repairs",
    "Courier & Mailroom Services",
    "Virtual Office Services",
    "Co-working Spaces",
    "Conference Room Rentals",
    "Notary Public Services",
    "Document Attestation",
    "Visa Application Centres",
    "Typing & Word Processing",
    "Data Entry Services",
    "Call Centre Services",
    "Customer Support Outsourcing",

    // ── Education Supplies & Services ───────────────────────────────
    "Bookshops & Stationery",
    "School Uniform Suppliers",
    "Educational Toy Shops",
    "School Bag & Supply Shops",
    "Exam Prep Materials",
    "Library Services",
    "E-Learning Centres",
    "Study Groups & Tutoring Hubs",

    // ── Food Processing & Cottage Industry ──────────────────────────
    "Chin Chin & Snack Production",
    "Puff Puff & Buns Production",
    "Groundnut Oil Processing",
    "Palm Kernel Oil Processing",
    "Garri Processing",
    "Yam Flour (Elubo) Production",
    "Ogiri & Locust Bean Production",
    "Crayfish & Dried Fish Sellers",
    "Smoked Fish Sellers",
    "Frozen Food Sellers",
    "Ice Block Makers",
    "Sachet & Bottled Water Production",
    "Fruit Juice Production",
    "Yoghurt & Dairy Products",
    "Honey & Natural Products",
    "Spice & Seasoning Sellers",
    "Tomato & Pepper Paste Sellers",

    // ── Fashion & Accessories ────────────────────────────────────────
    "Native Wear & Agbada Tailors",
    "Wedding Dress & Bridal Wear",
    "Children's Fashion",
    "Men's Fashion & Suits",
    "Women's Fashion & Boutiques",
    "Sportswear & Activewear",
    "Lingerie & Underwear Shops",
    "Caps & Hats Sellers",
    "Belts & Wallets",
    "Sunglasses & Eyewear",
    "Wristwatches & Clocks",
    "Costume Jewellery",
    "Gold & Silver Jewellery",
    "Beaded Jewellery Makers",
    "Leather Sandals & Slippers",
    "Sneakers & Sports Shoes",
    "Corporate Shoes",

    // ── Home & Lifestyle ─────────────────────────────────────────────
    "Home Cleaning Products",
    "Air Fresheners & Deodorisers",
    "Mosquito Nets & Repellents",
    "Insecticides & Pesticides",
    "Brooms & Mops Sellers",
    "Buckets & Plastic Wares",
    "Aluminium Pots & Cookware",
    "Gas Cookers & Stoves",
    "Microwave & Oven Sales",
    "Blenders & Kitchen Appliances",
    "Water Dispensers & Coolers",
    "Fans & Air Coolers",
    "Ceiling Fans Installation",
    "Curtain & Blinds Makers",
    "Rugs & Carpets",
    "Wall Clocks & Decorations",
    "Picture Frames & Artwork",
    "Candles & Lanterns",
    "Storage Boxes & Organisers",

    // ── Health & Pharmacy ────────────────────────────────────────────
    "Optical Shops & Glasses",
    "Hearing Aid Centres",
    "Orthopaedic Supplies",
    "Medical Equipment Sales",
    "Surgical Supplies",
    "First Aid Supplies",
    "Baby Formula & Nutrition",
    "Vitamins & Supplements",
    "Family Planning Services",
    "HIV/AIDS Testing Centres",
    "Malaria Testing & Treatment",
    "Tuberculosis Clinics",
    "Sickle Cell Centres",
    "Cancer Screening Centres",
    "Fertility Clinics",
    "Cosmetic Surgery Clinics",
    "Tattoo Removal",
    "Skin Lightening Clinics",
    "Hair Transplant Clinics",

    // ── Transport & Logistics ────────────────────────────────────────
    "Okada & Keke Napep Services",
    "Tricycle (Keke) Hire",
    "Motorcycle Spare Parts",
    "Truck Spare Parts",
    "Towing Services",
    "Vehicle Tracking Services",
    "Driving Licence Services",
    "Vehicle Registration Services",
    "Number Plate Makers",
    "Tinted Glass Services",
    "Car Audio & Accessories",
    "Car Seat Covers",
    "Fuel Delivery Services",

    // ── Agriculture Inputs & Services ───────────────────────────────
    "Seedlings & Nursery Plants",
    "Organic Farming Supplies",
    "Crop Insurance Services",
    "Agricultural Consulting",
    "Farm Labour Services",
    "Tractor Hire Services",
    "Irrigation Consultants",
    "Aquaculture Supplies",
    "Livestock Feed Sellers",
    "Veterinary Drugs & Supplies",
    "Poultry Equipment Suppliers",
    "Hatchery Services",
    "Abattoir Services",
    "Meat & Poultry Wholesale",

    // ── Real Estate & Property ───────────────────────────────────────
    "Short-Let Apartments",
    "Serviced Apartments",
    "Student Hostels & Accommodation",
    "Guesthouses",
    "Furnished Apartments",
    "Land Sales",
    "Commercial Property Sales",
    "Industrial Property",
    "Property Inspection Services",
    "Facility Management",
    "Estate Security Services",
    "Property Cleaning Services",
    "Plumbing for New Buildings",
    "Electrical for New Buildings",

    // ── Media, Arts & Culture ────────────────────────────────────────
    "Radio Stations",
    "TV Stations",
    "Online News Platforms",
    "Magazines & Periodicals",
    "Book Publishing",
    "Music Labels & Studios",
    "Talent Agencies",
    "Modelling Agencies",
    "Acting Schools",
    "Comedy & Entertainment Agencies",
    "Cultural Centres",
    "Art Studios",
    "Craft Workshops",
    "Pottery & Ceramics",
    "Sculpture Studios",
    "Textile Art & Weaving",

    // ── Childcare & Family ───────────────────────────────────────────
    "Creches & Nurseries",
    "After-School Care",
    "Holiday Programmes",
    "Children's Party Venues",
    "Baby Shower Planners",
    "Naming Ceremony Planners",
    "Child Psychologists",
    "Paediatric Dentists",
    "Baby Clothing Shops",
    "Pram & Baby Gear Shops",
    "Maternity Clothing",
    "Breastfeeding Support",

    // ── Funeral & Memorial Services ──────────────────────────────────
    "Funeral Homes & Parlours",
    "Coffin & Casket Makers",
    "Hearse Services",
    "Grave Digging Services",
    "Memorial Printing Services",
    "Obituary & Tribute Services",
    "Embalming Services",
    "Cemetery Management",

    // ── Financial Technology ─────────────────────────────────────────
    "Fintech Companies",
    "Payment Gateway Providers",
    "Digital Lending Platforms",
    "Savings & Investment Apps",
    "Remittance Services",
    "Payroll Software",
    "Accounting Software",
    "POS Terminal Providers",
    "USSD Banking Services",

    // ── Miscellaneous Services ───────────────────────────────────────
    "Errand & Personal Assistant Services",
    "Concierge Services",
    "Handyman Services",
    "Home Maintenance Services",
    "Swimming Pool Maintenance",
    "Borehole Maintenance",
    "Septic Tank Emptying",
    "Waste Bin Rental",
    "Shredding Services",
    "Safe & Vault Services",
    "Noticeboards & Bulletin Boards",
    "Classified Ads Services",
    "Mystery Shopping Services",
    "Market Research Firms",
    "Survey & Data Collection",
    "Drone Services",
    "3D Printing Services",
    "Virtual Reality Services",
    "Augmented Reality Services",
];

// Subcategory aliases for search matching
export const CATEGORY_ALIASES: Record<string, string[]> = {
    "Supermarkets & Hypermarkets": ["supermarket", "hypermarket", "shoprite", "spar", "market"],
    "Provision Stores": ["provision", "kiosk", "mini mart", "corner shop"],
    "Mini Marts & Kiosks": ["kiosk", "mini mart", "provision store"],
    "Fast Food & Bukas": ["fast food", "buka", "canteen", "quick service"],
    "Mama Put & Local Canteens": ["mama put", "canteen", "local food", "buka"],
    "Suya & Pepper Soup Spots": ["suya", "pepper soup", "nkwobi", "isi ewu"],
    "Barbing Salons": ["barber", "haircut", "clipper", "barbershop"],
    "Beauty Salons & Hair Salons": ["salon", "hair", "stylist", "hairdresser"],
    "Dry Cleaning & Laundry": ["laundry", "dry cleaner", "ironing", "pressing"],
    "Auto Repairs & Mechanics": ["mechanic", "auto repair", "car repair", "workshop"],
    "Tyre Services & Vulcanisers": ["tyre", "vulcaniser", "puncture", "wheel"],
    "Car Wash & Detailing": ["car wash", "auto wash", "detailing", "car cleaning"],
    "Phone Repairs": ["phone fix", "screen repair", "mobile repair", "phone technician"],
    "Computer Repairs": ["computer fix", "laptop repair", "PC repair", "tech support"],
    "Generator Sales": ["generator", "gen", "power supply"],
    "Generator Repairs & Servicing": ["gen repair", "generator service", "inverter repair"],
    "Solar & Renewable Energy": ["solar", "solar panel", "renewable", "green energy"],
    "Inverter & Battery Sales": ["inverter", "battery", "UPS", "power backup"],
    "Dispatch Riders": ["delivery", "okada", "bike courier", "dispatch"],
    "Logistics & Courier Services": ["courier", "delivery", "logistics", "shipping"],
    "POS Services & Agents": ["POS", "point of sale", "cash withdrawal", "transfer"],
    "Mobile Money Agents": ["mobile money", "opay", "palmpay", "kuda"],
    "Welding & Fabrication": ["welder", "fabricator", "iron works", "gate maker"],
    "Bricklayers & Masons": ["bricklayer", "mason", "block layer", "concrete"],
    "Block Industry": ["cement blocks", "block moulding", "interlocking", "paving stones"],
    "Plumbing & Pipefitting": ["plumber", "plumbing", "pipe", "water supply"],
    "Electrical Installation": ["electrician", "electrical", "wiring", "installation"],
    "Tailoring & Fashion Design": ["tailor", "seamstress", "fashion designer", "sewing"],
    "Ankara & Aso-Oke Sellers": ["ankara", "aso-oke", "fabric", "traditional fabric"],
    "Poultry Farming": ["poultry", "chicken farm", "egg production", "broiler"],
    "Fish Farming & Aquaculture": ["fish farm", "catfish", "tilapia", "aquaculture"],
    "Filling Stations & Petrol Stations": ["filling station", "petrol", "fuel", "NNPC", "Total"],
    "Pharmacies & Chemists": ["pharmacy", "chemist", "drug store", "medicine"],
    "Hospitals & Clinics": ["hospital", "clinic", "medical centre", "health centre"],
    "Schools & Universities": ["school", "university", "college", "polytechnic"],
    "Private Tutors & Lesson Teachers": ["tutor", "lesson", "home teacher", "coaching"],
    "Event Planning & Management": ["event planner", "event organiser", "party planner"],
    "Wedding Planners": ["wedding", "bridal", "wedding planner", "wedding coordinator"],
    "Photography & Video": ["photographer", "videographer", "photo studio", "cinematographer"],
    "Legal Services & Law Firms": ["lawyer", "attorney", "solicitor", "law firm", "barrister"],
    "Accounting & Auditing": ["accountant", "auditor", "bookkeeper", "CPA"],
    "Real Estate Agents": ["real estate", "property agent", "estate agent", "realtor"],
    "Property Developers": ["property developer", "housing estate", "real estate developer"],
    "Security Companies": ["security", "guard", "surveillance", "protection"],
    "Fumigation & Pest Control": ["fumigation", "pest control", "exterminator", "rodent control"],
    "Churches": ["church", "parish", "cathedral", "chapel", "ministry"],
    "Mosques": ["mosque", "masjid", "islamic centre", "juma'at"],
    "NGOs & Non-Profits": ["NGO", "non-profit", "charity", "foundation", "CBO"],
    "Cybercafes & Business Centres": ["cybercafe", "business centre", "internet cafe", "printing"],
    "Printing & Publishing": ["printing", "publisher", "press", "typesetting"],
    "Graphic Design": ["graphic designer", "designer", "artwork", "branding"],
    "Digital Marketing": ["digital marketing", "online marketing", "SEO", "social media"],
    "Web Design & Development": ["web designer", "web developer", "website", "web developer"],
    "Software Development": ["software developer", "programmer", "app developer", "coder"],
    "Restaurants & Cafes": ["restaurant", "cafe", "eatery", "diner", "bistro"],
    "Hotels & Resorts": ["hotel", "resort", "lodge", "accommodation", "inn"],
    "Bakery & Confectionery": ["bakery", "bread", "cake", "pastry", "confectionery"],
    "Catering Services": ["catering", "caterer", "food service", "event catering"],
    "Gyms & Fitness Centres": ["gym", "fitness", "workout", "exercise", "health club"],
    "Spas & Wellness Centres": ["spa", "wellness", "relaxation", "massage", "beauty"],
    "Makeup Artists": ["makeup", "MUA", "beauty artist", "cosmetics"],
    "Nail Technicians & Nail Salons": ["nail", "manicure", "pedicure", "nail art"],
    "Wigs & Hair Extensions": ["wig", "hair extension", "weave", "lace front"],
    "Cosmetics & Beauty Products": ["cosmetics", "beauty products", "skincare", "makeup"],
    "Furniture & Decor": ["furniture", "decor", "interior", "home furnishing"],
    "Interior Design": ["interior designer", "interior decorator", "home design"],
    "Landscaping & Gardening": ["landscaping", "gardening", "lawn care", "horticulture"],
    "Travel Agencies": ["travel agent", "travel agency", "holiday", "vacation"],
    "Tour Operators": ["tour operator", "tour guide", "sightseeing", "excursion"],
    "Visa & Immigration Services": ["visa", "immigration", "passport", "travel documents"],
    "Freight Forwarding": ["freight", "shipping", "cargo", "import", "export"],
    "Customs Clearing Agents": ["customs", "clearing agent", "import duty", "customs broker"],
    "Haulage & Trucking": ["haulage", "trucking", "truck", "heavy duty", "logistics"],
    "Cold Storage & Refrigeration": ["cold storage", "freezer", "refrigeration", "cold room"],
    "Warehousing & Storage": ["warehouse", "storage", "depot", "distribution centre"],
    "Oil & Gas Services": ["oil", "gas", "petroleum", "upstream", "downstream"],
    "Telecommunications": ["telecom", "MTN", "Airtel", "Glo", "9mobile", "network"],
    "Internet Service Providers": ["ISP", "internet", "broadband", "fibre", "WiFi"],
    "CCTV & Surveillance Systems": ["CCTV", "surveillance", "security camera", "alarm"],
    "AC & Refrigeration Services": ["AC", "air conditioning", "fridge repair", "cooling"],
    "Washing Machine Repairs": ["washing machine", "appliance repair", "laundry machine"],
    "TV & Electronics Repairs": ["TV repair", "electronics repair", "screen repair"],
    "Key Cutting & Locksmith": ["locksmith", "key cutting", "lock repair", "safe"],
    "Photocopy & Scanning": ["photocopy", "scanning", "printing", "document services"],
    "Passport & ID Photo Studios": ["passport photo", "ID photo", "photo studio"],
    "Sign Writing & Signage": ["signage", "sign writer", "billboard", "banner"],
    "Uniform & Workwear Suppliers": ["uniform", "workwear", "corporate wear", "safety wear"],
    "Packaging Materials": ["packaging", "carton", "nylon", "bags", "wrapping"],
    "Candle & Soap Making": ["candle", "soap", "handmade", "artisan"],
    "Herbal Medicine & Naturopathy": ["herbal", "natural medicine", "traditional", "herbs"],
    "Pet Shops & Supplies": ["pet shop", "pet supplies", "dog", "cat", "aquarium"],
    "Flower Shops & Florists": ["florist", "flowers", "bouquet", "floral"],
    "Bookshops": ["bookshop", "bookstore", "books", "novels", "textbooks"],
    "Toy Shops": ["toys", "toy shop", "children's toys", "games"],
    "Bicycle Sales & Repairs": ["bicycle", "bike", "cycling", "cycle shop"],
    "Auction Houses": ["auction", "bidding", "auctioneer"],
    "Pawnshops": ["pawnshop", "pawn", "collateral loan"],
    "Money Lenders": ["money lender", "loan", "credit", "finance"],
    "Cooperative Societies": ["cooperative", "co-op", "thrift", "savings group"],
    "Thrift & Savings (Ajo/Esusu)": ["ajo", "esusu", "thrift", "daily contribution"],

    // ── New profession & trade aliases ──────────────────────────────
    "Tailors & Seamstresses": ["tailor", "seamstress", "sewing", "clothes maker"],
    "Carpenters": ["carpenter", "woodwork", "joinery", "cabinet maker"],
    "Plumbers": ["plumber", "plumbing", "pipe repair", "water leak"],
    "Electricians": ["electrician", "wiring", "electrical repair"],
    "Mechanics": ["mechanic", "car repair", "engine repair", "auto workshop"],
    "Refrigerator & Freezer Technicians": ["fridge repair", "freezer repair", "refrigerator technician"],
    "Air Conditioner Technicians": ["AC repair", "air conditioner repair", "AC technician"],
    "Mobile Phone Repairers": ["phone repair", "screen repair", "phone technician", "mobile repair"],
    "Computer Engineers": ["computer engineer", "IT engineer", "hardware engineer"],
    "Laptop & Computer Repairers": ["laptop repair", "computer repair", "PC repair"],
    "Drivers (Private & Commercial)": ["driver", "private driver", "chauffeur"],
    "Security Guards": ["security guard", "guard", "watchman", "security man"],
    "Farm Produce Sellers": ["farm produce", "fresh produce", "foodstuff", "food items"],
    "Fresh Vegetable Sellers": ["vegetables", "fresh veg", "tomatoes", "pepper", "onion"],
    "Fresh Fruit Sellers": ["fruits", "fresh fruit", "banana", "orange", "mango"],
    "Car Spare Parts": ["spare parts", "car parts", "auto parts", "engine parts"],
    "Motorcycle Spare Parts Dealers": ["bike parts", "motorcycle parts", "okada parts"],
    "Mobile Phone Shops": ["phone shop", "mobile phone", "smartphone", "phone dealer"],
    "Computer Shops": ["computer shop", "laptop shop", "PC shop", "computer dealer"],
    "Computer Accessories Shops": ["computer accessories", "keyboard", "mouse", "monitor"],
    "Painters": ["painter", "painting", "wall painting", "house painting"],
    "Welders": ["welder", "welding", "fabrication", "metal work"],
    "Nannies & Babysitters": ["nanny", "babysitter", "childminder", "child care"],
    "Cooks & Private Chefs": ["cook", "private chef", "home cook", "personal chef"],
    "Gardeners & Landscapers": ["gardener", "landscaper", "lawn care", "garden maintenance"],
    "Photographers": ["photographer", "photo studio", "photography"],
    "Tutors & Home Teachers": ["tutor", "home teacher", "lesson teacher", "private lesson"],
    "Fitness Trainers": ["fitness trainer", "personal trainer", "gym trainer"],
    "Bodyguards": ["bodyguard", "VIP protection", "personal security"],
    "Truck Drivers": ["truck driver", "lorry driver", "haulage driver"],
    "Bakers": ["baker", "bread maker", "pastry chef", "confectioner"],
    "Caterers": ["caterer", "catering", "food service", "event food"],
    "Housekeepers": ["housekeeper", "house help", "domestic worker", "cleaner"],
    "Tilers": ["tiler", "tiling", "floor tiling", "wall tiles"],
    "Roofers": ["roofer", "roofing", "roof repair", "roof installation"],
    "Bricklayers": ["bricklayer", "mason", "block layer"],
    "Plasterers": ["plasterer", "plastering", "rendering", "screeding"],
    "Glaziers (Glass Fitters)": ["glazier", "glass fitter", "window glass", "glass installation"],
    "Blacksmiths": ["blacksmith", "iron work", "metal fabrication"],
    "Fumigators": ["fumigator", "fumigation", "pest control", "exterminator"],
    "Shoe Cobblers & Repairers": ["cobbler", "shoe repair", "shoe mender"],
    "Watchmakers & Watch Repairers": ["watch repair", "watchmaker", "clock repair"],
    "Satellite & DSTV Installers": ["DSTV installer", "satellite dish", "decoder installation"],
    "Generator Technicians": ["generator repair", "gen technician", "generator servicing"],
    "Solar Panel Installers": ["solar installer", "solar panel installation", "solar technician"],
    "Inverter Technicians": ["inverter repair", "inverter installation", "battery technician"],
    "Network Engineers": ["network engineer", "network setup", "LAN", "WiFi installation"],
    "IT Support Technicians": ["IT support", "tech support", "computer help", "IT technician"],
    "Printer Repairers": ["printer repair", "printer technician", "copier repair"],
    "Washing Machine Technicians": ["washing machine repair", "laundry machine repair"],
    "TV & Electronics Technicians": ["TV repair", "electronics repair", "screen repair"],
    "CCTV & Alarm Installers": ["CCTV installation", "alarm system", "security camera"],
    "Organic Produce Sellers": ["organic food", "organic produce", "natural food"],
    "Frozen Food Sellers": ["frozen food", "frozen chicken", "frozen fish", "frozen meat"],
    "Rice Sellers (Local & Foreign)": ["rice seller", "rice dealer", "ofada rice", "foreign rice"],
    "Palm Oil Sellers": ["palm oil", "red oil", "cooking oil"],
    "Crayfish & Stockfish Sellers": ["crayfish", "stockfish", "dried fish", "eja osan"],
    "Egg Sellers": ["eggs", "egg seller", "poultry eggs", "farm eggs"],
    "Honey Sellers": ["honey", "natural honey", "bee honey"],
    "Garri Sellers": ["garri", "cassava flakes", "eba"],
    "Yam & Cassava Sellers": ["yam", "cassava", "tubers", "food crops"],
    "Smartphone Dealers": ["smartphone", "android phone", "iPhone", "mobile phone"],
    "Used (Tokunbo) Phone Dealers": ["tokunbo phone", "used phone", "second hand phone"],
    "Used (Tokunbo) Laptop Dealers": ["tokunbo laptop", "used laptop", "second hand laptop"],
    "Gaming PCs & Consoles": ["gaming PC", "PlayStation", "Xbox", "Nintendo", "gaming console"],
    "Private Car Hire Drivers": ["car hire", "private driver", "hire car", "chauffeur service"],
    "Airport Transfer Services": ["airport transfer", "airport pickup", "airport drop off"],
    "Wedding Car Hire": ["wedding car", "bridal car", "wedding transport"],
    "Security Guard Companies": ["security company", "security firm", "guard service"],
    "VIP Protection & Bodyguards": ["VIP security", "bodyguard service", "executive protection"],
};
