export const DEMO_BUSINESSES = [
    {
        id: '1',
        name: 'Eko Hotels & Suites',
        category: 'Hotels',
        address: 'Plot 1415 Adetokunbo Ademola Street, Victoria Island',
        city: 'Lagos',
        state: 'Lagos',
        phone: '+234 800 123 4567',
        rating: 4.8,
        reviews: 1250,
        isVerified: true,
        openingTime: 'Open 24 hours',
        closingTime: '',
        tags: ['Luxury Hotel', 'Pool', 'Spa'],
        image: '/images/eko-hotels.jpg'
    },
    {
        id: '2',
        name: 'Chicken Republic',
        category: 'Restaurants',
        address: 'Adetokunbo Ademola Cres, Wuse 2',
        city: 'Abuja',
        state: 'FCT',
        phone: '+234 800 777 7777',
        rating: 4.5,
        reviews: 890,
        isVerified: true,
        openingTime: '9:00 AM',
        closingTime: '9:00 PM',
        tags: ['Dine-in', 'Takeaway', 'Delivery'],
        image: '/images/chicken-republic.jpg'
    },
    {
        id: '3',
        name: 'Dangote Cement Depot',
        category: 'Manufacturing',
        address: 'Obajana Plant Road',
        city: 'Lokoja',
        state: 'Kogi',
        phone: '+234 810 000 0000',
        rating: 4.2,
        reviews: 45,
        isVerified: true,
        openingTime: '7:00 AM',
        closingTime: '5:00 PM',
        tags: ['Wholesale', 'Cement', 'Logistics'],
        image: '/images/dangote.jpg'
    },
    {
        id: '4',
        name: 'Mama Nkechi Kitchen',
        category: 'Restaurants',
        address: '15 Douglas Road',
        city: 'Owerri',
        state: 'Imo',
        phone: '+234 901 234 5678',
        rating: 4.9,
        reviews: 320,
        isVerified: true,
        openingTime: '8:00 AM',
        closingTime: '8:00 PM',
        tags: ['Local Delicacies', 'Catering'],
        image: '/images/mama-kitchen.jpg'
    },
    {
        id: '5',
        name: 'FixIt Mechanics',
        category: 'Automotive',
        address: 'Ladipo Market Road',
        city: 'Lagos',
        state: 'Lagos',
        phone: '+234 700 227 3498',
        rating: 4.0,
        reviews: 15,
        isVerified: false,
        openingTime: '8:00 AM',
        closingTime: '6:00 PM',
        tags: ['Repairs', 'Maintenance'],
        image: '/images/mechanic.jpg'
    },
    {
        id: '6',
        name: 'Zenith Bank HQ',
        category: 'Finance',
        address: 'Plot 84 Ajose Adeogun Street, VI',
        city: 'Lagos',
        state: 'Lagos',
        phone: '+234 1 278 7000',
        rating: 4.6,
        reviews: 2100,
        isVerified: true,
        openingTime: '8:00 AM',
        closingTime: '4:00 PM',
        tags: ['Banking', 'ATM', 'Financial Services'],
        image: '/images/zenith.jpg'
    }
];
